[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
evm_version = "shanghai"
coverage = true

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/416304afa6a24e61934cad318b64884c"
